apiVersion: batch/v1
kind: Job
metadata:
  namespace: spanner-ns
  name: ycsb-java-zipfian
spec:
  completions: 5
  parallelism: 5
  completionMode: Indexed
  backoffLimit: 0
  activeDeadlineSeconds: 18000
  ttlSecondsAfterFinished: 86400
  template:
    metadata:
      labels:
        app: ycsb-java-zipfian
    spec:
      restartPolicy: Never
      containers:
        - name: ycsb-client
          image: us-west1-docker.pkg.dev/outbound-flight/spanner-box/ycsb-client:with-metrics-support
          imagePullPolicy: Always
          args:
            - run
            - cloudspanner
            - -P
            - workloads/workloadb
            - -P
            - cloudspanner/conf/cloudspanner.properties
            - -p
            - recordcount=1000000000
            - -p
            - zeropadding=12
            - -p
            - insertorder=ordered
            - -p
            - operationcount=1000000000000
            - -p
            - maxexecutiontime=3600
            - -p
            - requestdistribution=zipfian
            - -p
            - requestpartition.count=1
            - -p
            - requestpartition.index=$(JOB_COMPLETION_INDEX)
            - -p
            - requestpartition.size=1000000000
            - -threads
            - "20"
            - -s
          resources:
            requests:
              cpu: "7"
              memory: "25Gi"
            limits:
              cpu: "7"
              memory: "25Gi"
          env:
            - name: JOB_COMPLETION_INDEX
              valueFrom:
                fieldRef:
                  fieldPath: metadata.annotations['batch.kubernetes.io/job-completion-index']
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: OTEL_PROJECT_ID
              value: "outbound-flight"
            - name: OTEL_SERVICE_NAME
              value: "ycsb-cloudspanner"
            - name: OTEL_METRIC_PREFIX
              value: "custom.googleapis.com/ycsb/grpc_gcp"
            - name: OTEL_METRIC_EXPORT_INTERVAL_SECONDS
              value: "10"
            - name: YCSB_ENABLE_OTEL_TRACING
              value: "true"
            - name: YCSB_ENABLE_PERFMARK
              value: "true"
            - name: YCSB_PERFMARK_TRACE_FILE
              value: "/tmp/perfmark-$(POD_NAME).html"
            - name: YCSB_PERFMARK_TRIGGER_FILE
              value: "/tmp/perfmark-$(POD_NAME).trigger"
            - name: SPANNER_USE_OPENTELEMETRY_TRACING
              value: "true"
            - name: SPANNER_ENABLE_API_TRACING
              value: "true"
            - name: SPANNER_ENABLE_EXTENDED_TRACING
              value: "false"
            - name: SPANNER_ENABLE_END_TO_END_TRACING
              value: "false"
            - name: JAVA_TOOL_OPTIONS
              value: "-Xms16g -Xmx16g -XX:+AlwaysPreTouch -XX:+UseG1GC"
